"""empty message

Revision ID: d7bbbe269b0f
Revises: 
Create Date: 2021-08-26 22:55:15.376728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bbbe269b0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CategoriaItem',
    sa.Column('codigo_categoria_item', sa.Integer(), nullable=False),
    sa.Column('descricao_categoria_item', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('codigo_categoria_item')
    )
    op.create_table('Cliente',
    sa.Column('codigo_cliente', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=200), nullable=False),
    sa.Column('email_cliente', sa.String(length=200), nullable=False),
    sa.Column('telefone_celular', sa.String(length=23), nullable=False),
    sa.PrimaryKeyConstraint('codigo_cliente')
    )
    op.create_table('Item',
    sa.Column('codigo_item', sa.Integer(), nullable=False),
    sa.Column('descricao_item', sa.String(length=100), nullable=False),
    sa.Column('valor_unitario_item', sa.Float(), nullable=False),
    sa.Column('codigo_categoria_item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_categoria_item'], ['CategoriaItem.codigo_categoria_item'], ),
    sa.PrimaryKeyConstraint('codigo_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Item')
    op.drop_table('Cliente')
    op.drop_table('CategoriaItem')
    # ### end Alembic commands ###
